name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run ordinary black-box tests
      env:
        POCKET_OID_MANUAL_CODE_FLOW: "0"
        POCKET_OID_MANUAL_REAUTH: "0"
        POCKET_OID_MANUAL_KEYCLOAK_REAUTH: "0"
        POCKET_OID_SELENIUM_CODE_FLOW: "0"
      run: python3 -m unittest discover -s tests_blackbox -v
